### PR TITLE
Make modifiers and buttons tuples for immutability

### PR DESCRIPTION
**Pull request by hmaarrfk**
- [x] Tested Qt
- [x] Tested GLFW

xref: https://github.com/pygfx/pygfx/pull/731

### CODE REVIEW

**Comment by almarklein** [comment]
Mind the `list(self._pointer_buttons)` where the event dict is created.

**Comment by hmaarrfk** [comment]
> Mind the list(self._pointer_buttons) where the event dict is created.

Thank you.

This prompted me to go through the occurances of `[` and `list` in both the modified files.

**Comment by hmaarrfk** [comment]
i don't really know how to run glfw lol. so i wanted to highlight that.

**Comment by almarklein** [comment]
> i don't really know how to run glfw 

If you ``pip install glfw``, and run any of the examples that use `wgpu.gui.auto`, they will most likely use glfw, because its preferred over Qt. It will also show in the window title:
image

**Comment by hmaarrfk** [comment]
image_click_events.py image

fly_controller.py image

seems to work.

**Review by Korijn — APPROVED** [review]

**Pull request merged**
