### PR TITLE
Add tests for object releasing

### LINKED ISSUE #275: Rust panic after creating hundreds of renderers/canvases
I still need to figure out how to reliably reproduce this, but in a script I was batch running yesterday, my computer would actually lock up* after a rust panic. The problem went away after I modified the script to reuse the same canvas and renderer instance, instead of creating new ones for every image I was drawing.

\* Lock up as in, no response to ctrl+c, windows task manager would not respond, ctrl+alt+del does nothing, shutting down/rebooting gets stuck in a black screen... only way out was to hold the power button for 30 seconds.

### LINKED ISSUE #353: Investigate memoryleaks
In #306 we explored the memoryleak of Lavapipe, and found out that Device objects leak memory on Windows too. To be fair, in practice you'd likely only use one device per process, but there are use cases for using multiple devices. Let's also do some testing on other objects, and report/fix errors upstream.

The purpose of this issue is to track known leaks. We want wgpu-py to be a reliable system without leaks.

### Status

* Adapter
  * [ ] All systems: Memory does grow, albeit very slowly. Could be a small leak?
* Device
  * [ ] LavaPipe with Vulkan: Leaks significantly. 
  * [ ] Windows with Vulkan/D3D12: Leaks significantly. Crashes at the 64th iter! 
  * [ ] MacOS with Metal: Does not seem to leak.
* Buffer
* Texture
* ...

----

Code to track (updated):
```py
import gc
import psutil

import wgpu.backends.rs
import wgpu


p = psutil.Process()


def print_mem_usage(i):
    megs = p.memory_info().rss / 1024**2
    print(f"memory usage (round: {i}): {megs:.3f} MB")


if __name__ == "__main__":
    print_mem_usage(0)
    for i in range(500):
        adapter = wgpu.request_adapter(canvas=None, power_preference="high-performance")
        device = adapter.request_device()
        device.destroy()
        del device
        wgpu.backends.rs.delayed_releaser.release_all_pending()
        gc.collect()
        print_mem_usage(i + 1)

    wgpu.print_report()
```

### PR DESCRIPTION
**Pull request by almarklein**
Closes #353

This adds tests, in a new folder so it won't interfere with the unit tests. The idea is basically, doing for each kind of object:

* Get how many objects we have of each kind.
* Create a bunch of objects of a specific kind.
* Make sure the counts are indeed up.
* Delete the objects. 
* Check that the counts are down.

Todo:

* [x] Generic logic that is the same for each unit test.
* [x] Implement some meta-tests to make sure that the tests indeed fail when they should. 
* [x] Implement a test function for every object.
* [x] Can we *now* remove that `delayed_releaser`? Yes!
* [x] Can we *now* enable some release calls that previously panicked? Yes!
* [x] ~Measure process memory consumption to detect leaks?~ --> #406
* [x] Do we want our `BindGroupLayout` object to cache instances like wgpu-core does?
* [ ] Does this close #275?
* [x] Investigate fails:
    * [ ] Device (simply does not clean up in native).
    * [ ] Queue (related to the above)
    * No luck yet.
    * Following up in #405

### CODE REVIEW

**Comment by Korijn** [comment]
Can you explain what polling the device does conceptually?

**Comment by almarklein** [comment]
> Can you explain what polling the device does conceptually?

From what I understand, wgpu has an an event-loop of sorts, so it can perform asynchronous tasks. Polling the device flushes the device's queue. We also use poll in the functions that are asyn in nature, like buffer mapping. Related to #391.

**Comment by almarklein** [comment]
I think this is good to go. I'll have a look (probably after the weekend) what the state of #275 is. But in the mean time this is ready for review.

**Comment by almarklein** [comment]
I created 2 new issues for follow-up work.

**Review by Korijn — APPROVED** [review]

**Pull request merged**
