### PR TITLE
Codegen uses in-memory file system

### LINKED ISSUE #294: Windows/Linux line endings break a test during first execution only
This is an interesting one. The first time I ran the tests in a fresh/clean dev environment, one of the tests broke (`codegen/tests/test_codegen_z.py::test_that_code_is_up_to_date`). However, when I tried to re-run the test it passed nicely and since then subsequent re-runs also pass. I have put the full log of the run that broke below for future reference.

From what I can gather, the test in question modifies a file using codegen (not 100% sure what this is yet) and then checks if the content has changed as expected. The problem is that the file was originally created with windows-style line endings; however, after codegen has processed it, this switches to linux-style line endings which breaks the test.

On top of this, it looks like this original file gets permanently modified and changed to Linux-style line endings. As a result, the test passes for subsequent runs after the first.

So there seem to be two issues here, one regarding the linux/windows line ending and one regarding the test permanently changing a file and thus "bleeding" into subsequent runs (which isn't ideal from a testing standpoint). 

Overall, this only seems to have a small impact, so maybe we can afford not worry about this for now; however, I thought I should at least bring it up, so that it is tracked.

---

<details>
<summary>Full Test Log</summary>

```
(.venv) PS C:\Users\Sebastian\Documents\Coding-Projects\wgpu-py> pytest
===================================================================================== test session starts ======================================================================================
platform win32 -- Python 3.8.8, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\Users\Sebastian\Documents\Coding-Projects\wgpu-py
collected 98 items / 1 skipped

codegen\tests\test_codegen_apipatcher.py ..                                                                                                                                               [  2%] 
codegen\tests\test_codegen_rspatcher.py ..                                                                                                                                                [  4%]
codegen\tests\test_codegen_utils.py .......                                                                                                                                               [ 11%]
codegen\tests\test_codegen_z.py F.                                                                                                                                                        [ 13%]
examples\tests\test_examples.py .....ss                                                                                                                                                   [ 20%]
tests\test_api.py ........                                                                                                                                                                [ 28%]
tests\test_compute.py ........                                                                                                                                                            [ 36%]
tests\test_gui_auto_offscreen.py ..                                                                                                                                                       [ 38%] 
tests\test_gui_base.py ....                                                                                                                                                               [ 42%]
tests\test_rs_basics.py ..................                                                                                                                                                [ 61%]
tests\test_rs_compute_tex.py ............                                                                                                                                                 [ 73%]
tests\test_rs_render.py ...........                                                                                                                                                       [ 84%]
tests\test_rs_render_tex.py .............                                                                                                                                                 [ 97%]
wgpu\__pyinstaller\test_wgpu.py ..                                                                                                                                                        [100%]

=========================================================================================== FAILURES =========================================================================================== 
_________________________________________________________________________________ test_that_code_is_up_to_date _________________________________________________________________________________ 

    def test_that_code_is_up_to_date():
        """Test that running the codegen updates what we expect, but does not introduce changes."""

        # Obtain mtime of all files
        mtimes = {}
        for root, dirs, files in os.walk(lib_dir):
            if "__pycache__" in root:
                continue
            for fname in files:
                filename = os.path.join(lib_dir, root, fname)
                mtimes[filename] = os.path.getmtime(filename)

        # Give it some time
        time.sleep(0.2)
        ref_time = time.time()
        time.sleep(0.2)

        assert all(t < ref_time for t in mtimes.values())

        # Create cache
        file_cache = {}
        for filename in changing_files:
            assert os.path.isfile(filename)
            with open(filename, "rb") as f:
                file_cache[filename] = f.read()

        # Double-check that mtimes have not changed
        all(t == os.path.getmtime(filename) for filename, t in mtimes.items())

        # Apply codegen
        main()

        # Get files that have changed
        updated = {
            filename for filename, t in mtimes.items() if t != os.path.getmtime(filename)
        }

        # Check that exactly the files updated that we expected
        assert updated == changing_files

        # But they should not have changed
        for filename in changing_files:
            content1 = file_cache[filename]
            with open(filename, "rb") as f:
                content2 = f.read()
>           assert content1 == content2
E           assert b'"""\r\nThe ...lobals())\r\n' == b'"""\nThe cl...(globals())\n'
E             At index 3 diff: b'\r' != b'\n'
E             Use -v to get more diff

codegen\tests\test_codegen_z.py:68: AssertionError
------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------- 
# Code generatation report
## Preparing
* The webgpu.idl defines 35 classes with 75 functions
* The webgpu.idl defines 5 flags, 33 enums, 58 structs
* The wgpu.h defines 131 functions
* The wgpu.h defines 5 flags, 48 enums, 74 structs
## Updating API
* Wrote 5 flags to flags.py
* Wrote 33 enums to enums.py
* Wrote 58 structs to structs.py
### Patching API for base.py
* Diffs for GPU: change request_adapter, change request_adapter_async
* Diffs for GPUCanvasContext: add present
* Diffs for GPUAdapter: add properties
* Diffs for GPUDevice: add adapter, add create_buffer_with_data, hide import_external_texture, hide pop_error_scope, hide push_error_scope
* Diffs for GPUBuffer: add map_read, add map_write, add size, add usage, hide get_mapped_range, hide map_async, hide unmap
* Diffs for GPUTexture: add dimension, add format, add mip_level_count, add sample_count, add size, add usage
* Diffs for GPUTextureView: add size, add texture
* Diffs for GPUQueue: add read_buffer, add read_texture, hide copy_external_image_to_texture
* Validated 35 classes, 102 methods, 35 properties
### Patching API for backends/rs.py
* Diffs for GPUAdapter: add request_device_tracing
* Validated 35 classes, 92 methods, 0 properties
## Validating rs.py
* Enum field FeatureName.shader-f16 missing in wgpu.h
* Enum CanvasCompositingAlphaMode missing in wgpu.h
* Wrote 231 enum mappings and 49 struct-field mappings to rs_mappings.py
* Validated 80 C function calls
* Not using 56 C functions
* Validated 70 C structs
======================================================================================= warnings summary ======================================================================================= 
.venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py:20
  c:\users\sebastian\documents\coding-projects\wgpu-py\.venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================================== short test summary info ==================================================================================== 
FAILED codegen/tests/test_codegen_z.py::test_that_code_is_up_to_date - assert b'"""\r\nThe ...lobals())\r\n' == b'"""\nThe cl...(globals())\n'
================================================================ 1 failed, 95 passed, 3 skipped, 1 warning in 61.90s (0:01:01) ================================================================= 
```

</details>

### PR DESCRIPTION
**Pull request by almarklein**
Closes #294

This makes the codegen use a simple in-memory file system. This makes the test have no side-effect on the code, and it's easier to write the changed files with the correct line-endings.

Implementation wise:
* [x] Wrote simple file system class in  new `files.py` module. A singleton is created.
* [x] Use that file system instead of the real file system in all codegen modules.
* [x] Move `main()` and its subfunctions from `__main__.py`  to `__init__.py`, so it can be easier imported.
* [x] The `main()` does not write to disk.
* [x] The `__main__.py`  calls `main()` and then writes to disk.

### CODE REVIEW

**Comment by almarklein** [comment]
I renamed "file system" to "file cache", which sounds less intimidating.

**Review by Korijn — APPROVED** [review]
Great work, this is a very nice improvement.

**Comment by almarklein** [comment]
@FirefoxMetzger could you check that with this change, running `python codegen` does not change the line endings? (i.e. an empty `git status`?)

**Comment by FirefoxMetzger** [comment]
Yep, that appears to do the trick. I ran the testsuite and now there are no modifications upon completion:

```
(.venv) PS C:\Users\Sebastian\Documents\Coding-Projects\wgpu-py> git status
HEAD detached at upstream/codegen
nothing to commit, working tree clean
```

**Pull request merged**
