### PR TITLE
Update to wgpu-native v0.14.2.3

### PR DESCRIPTION
**Pull request by almarklein**
From scanning the changes in the .h files:

* [x] Do we use errorfilter en errortype somewhere? It has a new "internal" field.  
* [x] Default limits :/  
* [x] Handling of features.
* [x] Buffer getsize and getusage  
* [x] Texture getheight and a lot more.  
* [x] `WGPUProcComputePassEncoderDispatch` -> `WGPUProcComputePassEncoderDispatchWorkgroups`
* [x] same for `WGPUProcComputePassEncoderDispatchIndirect`
* [x] Use `wgpuFree`. Not for logging. But needed for result of `wgpuSurfaceGetSupportedFormats` and `wgpuSurfaceGetSupportedPresentModes`.  
* [x] Logcallback now has userdata  
* [x] `wgpuRenderPassEncoderDrop`, `wgpuSurfaceDrop`, and more drop functions.  

Other tasks:
* [x] Make sure that the examples work.
* [x] Make sure that the tests pass.
* [x] Make sure that the pygfx tests pass locally too.
* [x] Re-release wgpu-native for the rows_per_image-hotfix.
* [x] Bump to the new wgpu-native.
* [x] Document changes in the release notes.

Copy from the changelog:
* To use the default `min_binding_size` in `create_bind_group_layout`, it should be `None` instead of zero.
* If the depth-stencil texture has not room for stencil data, the `stencil_read_mask` and `stencil_write_mask` fields in the `DepthStencilState` struct passed to `create_render_pipeline()` must be set to 0.
* In WGSL, `@stage(compute)` must now be `@compute`. Same for `vertex`  and `fragment`.
* In WGSL, the list of reserved words has been extended, including e.g. `mod`, `matrix` and `ref`.
* In WGSL, `smoothStep` is now `smoothstep`.

### CODE REVIEW

**Comment by Korijn** [comment]
I went over your work so far and didn't see anything out of the ordinary.

**Comment by almarklein** [comment]
This is close to finished, but I'm stuck on an error related to uploading 3D texture data. I'm starting to think this might be a bug in wgpu-core.
```
thread '<unnamed>' panicked at 'Unable to write texture: Transfer(BufferOverrun { start_offset: 0, end_offset: 329728, buffer_size: 12288, side: Source })', src/device.rs:743:6
```

**Comment by almarklein** [comment]
Having some bumps getting it to work in pygfx, related to validations failing for depth-stencil:
```
thread '<unnamed>' panicked at 'Unable to end render pass:
RenderPassError { scope: SetPipelineRender((12, 1, Metal)), inner: RenderCommand(IncompatiblePipelineRods) }',
src/command.rs:298:10
```

**Comment by almarklein** [comment]
*Sigh* ...  now the wheel building fails: "This does not look like a platform wheel"

**Comment by almarklein** [comment]
Nevermind, fixed it.

**Comment by almarklein** [comment]
Ready from my end!

**Comment by Korijn** [comment]
> PyGfx is up and running! 🚀 But ... _Sigh_ ... now the wheel building fails: "This does not look like a platform wheel"

So, it didn't fail silently! That's a good thing. :) Good job!

**Review by Korijn — APPROVED** [review]

**Comment by almarklein** [comment]
> So, it didn't fail silently! That's a good thing. :)

Well, the Linux build was the only one that failed. For some reason the Windows and MacOS build passed, even though they suffered from the same problem.

**Pull request merged**
