### PR TITLE
'QWgpuWidget' adds support for events, and delegate events of QWgpuCanvas' to subwidgets

### PR DESCRIPTION
**Pull request by panxinmiao**
So, can use "OrbitControls" , etc. on "QWgpuWidget"

### CODE REVIEW

**Comment by Korijn** [comment]
Looks like all you did was move things around and add a subclass, correct? Or did you also change the implementation of some methods?

**Comment by panxinmiao** [comment]
> Looks like all you did was move things around and add a subclass, correct? Or did you also change the implementation of some methods?

Yes, there is no change in any method implementation, only moved, so "QWgpuWidget" can also use "AutoGui" events

**Comment by Korijn** [comment]
In that case I think this is OK, @almarklein or @berendkleinhaneveld would you like to test this before we merge, perhaps?

**Comment by berendkleinhaneveld** [comment]
LGTM

**Comment by almarklein** [comment]
The diff is a bit hard to read (not your fault) but looks like a simple change indeed. LGTM! Thanks!

**Pull request merged**
