### PR TITLE
Glfw mouse position fix

### PR DESCRIPTION
**Pull request by almarklein**
This is (again) due to the fact that the meaning of screen space depends on the platform. We had a trick to detect the meaning, and in this PR we use the result to fix the pos in mouse events.

~Would be good if someone on Windows/Linux with a hidpi screen could check that the positioning still works well there. E.g using pygfx's picking_points.py example.~ Done :)

### CODE REVIEW

**Comment by Korijn** [comment]
Jaraco problem looks like a recent change in setuptools actually: https://github.com/pypa/setuptools/blob/main/CHANGES.rst

**Comment by almarklein** [comment]
I posted an issue: https://github.com/pyinstaller/pyinstaller/issues/6564  Let's merge this as-is.

**Comment by Korijn** [comment]
You can mark the test with xfail. That way CI will pass and we will know when the outcome changes again later

**Comment by almarklein** [comment]
I set the GH actions `continue-on-error`. Or did you mean the pytest xfail? :P   I think either way the error is hidden, right?

**Comment by Korijn** [comment]
Let's go with pytest; we don't want to ignore _all_ errors!

**Comment by almarklein** [comment]
>  we don't want to ignore all errors!

No, I only applied it to the pyinstaller step.

**Comment by almarklein** [comment]
Looks like a fix is underway in PyInstaller. Let's hold on for a bit.

**Pull request merged**
