### PR TITLE
Add missing dev dependencies

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
Closes: https://github.com/pygfx/wgpu-py/issues/293

This PR adds two missing dependencies to `dev-requirements.txt`

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
@Korijn RTR ... I guess 😅

**Review by Korijn — APPROVED** [review]

**Review by almarklein — APPROVED** [review]

**Comment by FirefoxMetzger** [comment]
@Korijn What is the procedure for merges? Will @almarklein do the merge or shall I? Also, who has to sign off on PRs? :)

**Comment by Korijn** [comment]
I'm not sure how to set this up in terms of branch protection, but the only hard requirement we have is that I have to approve every pull request (and we never commit to master directly).

**Comment by FirefoxMetzger** [comment]
Not sure if I understood this correctly, but I would advocate for explicitly preventing pushes to master/main if it isn't set up already. All it takes is a stupid mistake like tracking the wrong branch while making incremental commits that you think go to a PR branch.

Apart from that, @Korijn do you sign off on all PRs (outside of almar's and mine)? If so, you could enforce this by making yourself a code owner, and then setting it so that all PRs must have at least 1 [approval from a code owner](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging) before they can be merged. You can then choose if you prefer to be the one that merges or if anyone with write access can hit the button.

That said, as long as I know if I should wait after your approval or if I should merge the branch I'm happy :)

**Comment by almarklein** [comment]
mmm, I thought that this setting would prevent pusing directly to `main`. It [does not](https://github.com/pygfx/wgpu-py/commit/17ff58e94a3f6611c644a5f303f9ac2b20aa5f85) :)

image

**Pull request merged**
